### ISSUE TITLE
failures while running bundle install

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/sinatra-hello-world-basics#4]
nokogiri failed to install, @loganhasson helped me, i ended up having to run: 

`gem install nokogiri -v 1.6.6.2 -- --use-system-libraries`

the event machine filed to install, logan helped me with: 

`gem install eventmachine -v 1.0.7 -- --with-cppflags=-I/usr/local/opt/openssl/include`

**Comment by AnnJohn** [comment]
@vicfriedman did you see this issue when you were working on this lesson earlier? If so, you can just close.

**Comment by victhevenot** [comment]
i locked the gems, closing :)
