### ISSUE TITLE
http://localhost:9393 and the IDE

### ISSUE THREAD

**Issue by wendisha** [learn-co-curriculum/sinatra-hello-world-basics#6]
When working in the IDE, visiting http://localhost:9393 to test your web app wont work.
Please add a note, because it can get a little confusing.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
